SELECT b.name,
       b.slug,
       a.zcta5ce10

FROM public."tl_2019_us_zcta510" a
         JOIN core.regions b
              ON st_intersects(
                      st_transform(a.geom, 4326), st_transform(b.geometry, 4326))

WHERE b."name" not in (
                       'Earth',
                       'United States',
                       'Alberta',
                       'Yukon Territory',
                       'Northwest Territories',
                       'British Columbia',
                       'Manitoba',
                       'Ontario',
                       'Quebec',
                       'Nova Scotia'
                           'Saskatchewan',
                       'Nunavut',
                       'Newfoundland and Labrador',
                       'Mexico',
                       'Canada',
                       'Argentina',
                       'Uruguay',
                       'Alabama',
                       'Alaska',
                       'Arizona',
                       'Arkansas',
                       'California',
                       'Colorado',
                       'Connecticut',
                       'Delaware',
                       'Florida',
                       'Georgia',
                       'Hawaii',
                       'Idaho',
                       'Indiana',
                       'Illinois',
                       'Iowa',
                       'Kansas',
                       'Kentucky',
                       'Louisiana',
                       'Maine',
                       'Maryland',
                       'Massachusetts',
                       'Michigan',
                       'Minnesota',
                       'Mississippi',
                       'Missouri',
                       'Montana',
                       'Nebraska',
                       'Nevada',
                       'New Hampshire',
                       'New Jersey',
                       'New Mexico',
                       'New York',
                       'North Carolina',
                       'North Dakota',
                       'Ohio',
                       'Oklahoma',
                       'Oregon',
                       'Pennsylvania',
                       'Rhode Island',
                       'South Carolina',
                       'South Dakota',
                       'Tennessee',
                       'Texas',
                       'Utah',
                       'Vermont',
                       'Virginia',
                       'Washington',
                       'West Virginia',
                       'Wisconsin',
                       'Wyoming'
    )
  AND b."name" NOT LIKE '%Do Not Use%'